<#ftl encoding="utf-8" output_format="HTML" />

<#-- 
    This template aims to detail the instructions required to integrate
    with this Stencils using full and partial integration.
-->

<#import "/web/templates/modernui/funnelback_classic.ftl" as s/>
<#import "/share/stencils/libraries/base/client_includes.ftl" as client_includes />
<#import "auto_complete.ftl" as auto_complete />

<#-- Used to send absolute URLs for resources -->
<#assign httpHost=httpRequest.getHeader('host')>

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Search integration for ${question.collection.configuration.value("group.project_id")!}</title>
    <link href="https://unpkg.com/normalize.css@8.0.1/normalize.css" rel="stylesheet">
    <link href="/s/resources/${question.collection.id}/${question.profile}/css/main.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.0/css/all.css">

    <style>
        /* Basic styling for code snippets */
        pre {
            background: #f4f4f4;
            border: 1px solid #ddd;
            border-left: 3px solid #f36d33;
            color: #666;
            page-break-inside: avoid;
            font-family: monospace;
            font-size: 15px;
            line-height: 1.6;
            margin-bottom: 1.6em;
            max-width: 100%;
            overflow: auto;
            padding: 1em 1.5em;
            display: block;
            word-wrap: break-word;
        }
    </style>
</head>
<body>

    <#-- Output the clients global navigation -->
    <@client_includes.ContentHeader />
    
    <div class="fb-container">
        <main class="main" role="main">
            <section class="content-wrapper">
                <h1>Integrating with Funnelback Search</h1>

                <h2>Full integration</h2>
                <p>
                    In this option, Funnelback is responsible for generating a standalone HTML page with all 
                    the functionality of search. When users search on the main website, they will
                    be redirected to the Funnelback server to access search results.

                </p>
                <p>
                    Please note that this normally requires the user to navigate from one domain to another.
                </p>
                <pre>https://example.com -> https://search.example.com</pre>

                <p> 
                    To integrated with Funnelback search, simply include a form with an input which 
                    submits the users query to the appropriate endpoint. A basic example can be
                    found below:
                </p>

<#assign searchForm>
<form
    action="https://${httpHost!}/s/search.html" 
    method="GET"
    role="search">

    <input required 
        name="query" 
        id="query" 
        type="Search query"
        autocomplete="off" 
        placeholder="Start your search here…" 
        spellcheck="false" 
        dir="auto"
        aria-labelledby="fb-query"
        aria-required="true">

    <input type="hidden" name="collection" value="${question.collection.id!}">
    <input type="hidden" name="profile" value="${question.profile!}">
</form>
</#assign>
                <pre>${searchForm!?markup_string}</pre>


                <p> 
                    It will also be beneficial to implement Funnelback's autocomplete
                    which will improve the user's search experience. Please see
                    <a href="https://${httpHost!}/s/search.html?collection=${question.collection.id}&form=config-auto_complete">autocomplete configuration</a>
                    for more detail.   
                </p>                

                <h2>Partial integration</h2>
                <p>
                    With this method, Funnelback generates an HTML fragment rather 
                    than a full HTML page which can then be embedded into a webpage. 
                    The fragment is usually enclosed in a &lt;div&gt;&lt;/div&gt; or 
                    similar block level tag. This fragment will be embedded as-is inside 
                    the page generated by the Content Management System (CMS).
                </p>

                <p> 
                    Here are the links to the partial template for each profile: 
                    [<a href="https://${httpHost!}/s/search.html?collection=${question.collection.id}&profile=_default_preview&form=partial">Preview</a>]
                    [<a href="https://${httpHost!}/s/search.html?collection=${question.collection.id}&form=partial">Live</a>]
                </p>

                <em>Javscript libraries</em>
                <p> 
                    An optional but recommended step is to review the list of third party libraries
                    which are used by Funnelback and determine if the are already included
                    in the CMS. e.g. The relevant section in partial.ftl is provided below:
                </p>

<#-- Note: Indentation is off because the leading tabs are shown in the <pre> -->

<#assign requiredJavascript>
<!-- 
    TODO: Review the following libraries and see if they need they are already
    included by the CMS. If they are, simply comment out the relevant libraries.
-->
<!-- Third party libraries -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha512-hJSZLjaUow3GsiAkjUBMxN4eaFysMaBvg7j6mkBeo219ZGmSe1eVhKaJJAj5GzGoD0j0Gr2/xNDzjeecdg+OCw==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>    
<script src="https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.bundle.min.js" integrity="sha512-qOBWNAMfkz+vXXgbh0Wz7qYSLZp6c14R0bZeVX2TdQxWpuKr6yHjBIM69fcF8Ve4GUX6B6AKRQJqiiAmwvmUmQ==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.7.6/handlebars.min.js" integrity="sha512-zT3zHcFYbQwjHdKjCu6OMmETx8fJA9S7E6W7kBeFxultf75OPTYUJigEKX58qgyQMi1m1EgenfjMXlRZG8BXaw==" crossorigin="anonymous"></script>

<!-- The vendor.js file includes all the code from external libraries -->
<script type="text/javascript" src="https://${httpHost!}/s/resources/${question.collection.id}/${question.profile}/js/vendors.js"></script>
<!-- 
    Webpacks "runtime" code. Contains everything required to connect the
    modularized application while it’s running in the browser. It contains 
    the loading and resolving logic needed to connect your modules as they 
    interact.
-->
<script type="text/javascript" src="https://${httpHost!}/s/resources/${question.collection.id}/${question.profile}/js/runtime.js"></script>
<!-- Stencil specific code such as the quickview and dropdowns -->
<script type="text/javascript" src="https://${httpHost!}/s/resources/${question.collection.id}/${question.profile}/js/main.js"></script>

<!-- Stencils specific code -->
<script src="https://${httpHost!}/s/resources/${question.collection.id}/${question.profile}/js/stencils.js"></script>
<script src="https://${httpHost!}/s/resources/${question.collection.id}/${question.profile}/js/handlebars-helpers.js"></script>  

<!-- Funnelback auto-complete -->
<script src="https://${httpHost!}/s/resources/${question.collection.id}/${question.profile}/js/funnelback.autocompletion-2.6.0.stencils.js"></script>
</#assign>

                <pre>${requiredJavascript!?markup_string}</pre>

                <em>Styling the search</em>
                <p>
                    The next step is to style the search so that the implementation 
                    fits in with the overall look and feel of the website in the CMS.
                </p>

                <em>Supporting compare feature</em>

                <p>
                    The last step is to enable the compare/cart functionality which 
                    allows users to easily compare programs.
                    This feature makes use of browser cookies. 
                    An example of the cookie can be found below:
                </p>
                <pre>Set-Cookie: user-id=5bd95b96-e9f4-4b0a-9402-415e0bce065b; Expires=Thu, 24-Feb-2022 14:08:18 GMT; Max-Age=31536000</pre>
                <p>                    
                    Unfortunately, for security reasons, modern browsers places restrictions 
                    on cookies which are called from different domains.
                    This means that requests made to the compare/cart endpoint from a 
                    non-Funnelback domain are blocked by default.  

                    It is possible to get around this limitation by allowing the Funnelback 
                    endpoints to be referenced by the same domain as the website. 
                    This can be done by using any one of the following:
                </p>
                <ul>
                    <li>
                        Create a domain and point it to Funnelback. 
                        i.e. search.marvel.edu -> marvel.clients.us.funnelback.com. 
                        This will allow browsers to treat the "user-id" as a same-site cookie. 
                    </li>
                    <li>
                        Create a proxy via the CMS servers to act as a middle layer which
                        forwards traffic to Funnelback.                  
                    </li>
                <p>
                    For more details, please see the 
                    <a href="https://docs.squiz.systems/funnelback/knowledgebase/latest/kb-articles/implementation-guide-html-integration.html#session-cookie-domain">
                        Funnelback Knowledgebase.
                    </a>                    
                </p>

            </section>
        </main><!-- /.main -->
    </div>
    
    <@client_includes.ContentFooter />

</body>
</html>
